### PR TITLE
use debounce to fix color and add implement color temp

### PR DESCRIPTION
**Pull request by nedvisol**
#32 Fix for incorrect color set in Home app causing incorrect color and flickering lights, also add a feature for setting colorTemperature

### CODE REVIEW

**Comment by milo526** [comment]
Thanks for the PR! I'm currently at a campsite and unable to deploy a new version. Expect this to be merged in a week and deployed shortly after.

**Comment by bryan-stafford** [comment]
@nedvisol is there a way to install this pull request manually while we're waiting on a merge? I'd love to test this method with the brand of rbg bulbs that I have because your description of the issue looks and sounds like exactly what I'm experiencing. Beginner-level user here. I pulled down your code but I can't find a way to push a manual update to the plugin in the HOOBS interface. Is it possible?

**Comment by nedvisol** [comment]
You could install it straight from my Git branch for testing

1) uninstall the current homebridge-tuya-web plugin but don't remove the config from the config file
2) open up the console (either SSH to your server or use "Terminal" from Homebridge menu)
3) run `npm install -g nedvisol/homebridge-tuya-web#color-fix` .... this will pull the code from my branch on Github
note: if it throws an error, you might need to do prepend `sudo` in front of `npm`

Have fun! and let me know if you run into any issues.

**Comment by milo526** [comment]
Thank you very much for this PR once again. The issue as solved here have also been solved in the new beta branch `@milo526/homebridge-tuya-web@beta`. Your implementation using the debounce (something I had never heard of) helped my tremendously by solving a few issues this plugin had. 

Since the issues are solved in another way and this PR is now made on outdated code I will close this PR.

**Pull request closed without merging**
